# cSpell:disable
[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true
linemode = "size"
show_hidden = false
show_symlink = true
scrolloff = 5
mouse_events = [ "click", "scroll" ]
title_format = "Yazi: {cwd}"

[preview]
wrap = "yes"
tab_size = 4
max_width = 600
max_height = 900
cache_dir = ""
image_delay = 30
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
    { run =  '${EDITOR:-vim} "$@"', desc = "$EDITOR", block = true, for = "unix"},
    { run = 'nvim %*', desc = "nvim", for = "windows" },
    { run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	  { run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]

open = [
    { run = 'xdg-open "$1"', desc = "Open", for = "linux" },
    { run = 'open "$@"', desc = "Open", for = "macos" },
    { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]

reveal = [
    { run = 'xdg-open "$(dirname "$1")"',           desc = "Reveal", for = "linux" },
  	{ run = 'open -R "$1"',                         desc = "Reveal", for = "macos" },
	  { run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
]

extract = [
    { run = '7z x "%1" -o"%CD%"', desc = "Extract here (7-Zip)", for = "windows" },
    { run = '7z x "$1" -o"$PWD"', desc = "Extract here (7-Zip)", for = "unix" },
]

play = [
    { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
    { run = 'start "" "%1"', orphan = true, desc = "Play with default app", for = "windows" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[open]
rules = [
    { mime = "text/*", use = "edit" },          
    { mime = "video/*", use = "play" }, 

    { name = "*.json", use = "edit" }, 

    { name = "*.html", use = [ "open", "edit" ] },   
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912 # 512MB
image_bound      = [0, 0]
suppress_preload = false

[input]
cursor_blink = false

# cd
cd_title  = "Change directory:"
cd_origin = "top-center"
cd_offset = [0, 2, 50, 3]

# create
create_title  = ["Create:", "Create (dir):"]
create_origin = "top-center"
create_offset = [0, 2, 50, 3]

# rename
rename_title  = "Rename:"
rename_origin = "hovered"
rename_offset = [0, 1, 50, 3]

# trash
trash_title  = "Move {n} selected file{s} to trash? (y/N)"
trash_origin = "top-center"
trash_offset = [0, 2, 50, 3]

# delete
delete_title  = "Delete {n} selected file{s} permanently? (y/N)"
delete_origin = "top-center"
delete_offset = [0, 2, 50, 3]

# filter
filter_title  = "Filter:"
filter_origin = "top-center"
filter_offset = [0, 2, 50, 3]

# find
find_title  = ["Find next:", "Find previous:"]
find_origin = "top-center"
find_offset = [0, 2, 50, 3]

# search
search_title  = "Search via {n}:"
search_origin = "top-center"
search_offset = [0, 2, 50, 3]

# shell
shell_title  = ["Shell:", "Shell (block):"]
shell_origin = "top-center"
shell_offset = [0, 2, 50, 3]

# overwrite
overwrite_title  = "Overwrite an existing file? (y/N)"
overwrite_origin = "top-center"
overwrite_offset = [0, 2, 50, 3]

# quit
quit_title  = "{n} task{s} running, sure to quit? (y/N)"
quit_origin = "top-center"
quit_offset = [0, 2, 50, 3]

[pick]
open_title  = "Open with:"
open_origin = "hovered"
open_offset = [0, 1, 50, 7]

[which]
sort_by        = "none"
sort_sensitive = false
sort_reverse   = false
sort_translit  = false
